Release 19.0.0
theforeman/puppet-foreman pull request #1001
Opened 2021-10-24 17:20 UTC by ehelms

Potential PRs for release:

 - [x] https://github.com/theforeman/puppet-foreman/pull/1000
 - [x] https://github.com/theforeman/puppet-foreman/pull/965
 - [x] https://github.com/theforeman/puppet-foreman/pull/996
 - [x] https://github.com/theforeman/puppet-foreman/pull/981

2021-10-29 18:33 UTC, ekohl commented
I also want to look at dropping Ubuntu 18.04 and adding 20.04 (#981).

2021-11-09 13:56 UTC, ekohl requested changes
We should update https://github.com/theforeman/puppet-foreman#support-policy to say it's targeting 3.1 but with `register => false` it can work on 2.4+. It's fine to do that in this PR.

2021-11-09 16:38 UTC, ehelms commented on README.md
> +The module can be used with Foreman 2.4+ by setting `register_in_foreman => false`.
@ekohl Added

2021-11-09 19:30 UTC, ekohl approved these changes

2021-11-09 19:34 UTC, merged