Drop EL7 support
theforeman/puppet-foreman pull request #1061
Opened 2022-06-07 02:00 UTC by ehelms

2022-06-07 16:06 UTC, jhoblitt commented
Please don't drop EL7 yet... I'm still working on migrating my production foreman deployments to EL8.

2022-06-08 01:34 UTC, ehelms commented
> Please don't drop EL7 yet... I'm still working on migrating my production foreman deployments to EL8

Can you share your timeline? We've been communicating this drop [1] and timeline [2].

[1] https://community.theforeman.org/t/deprecation-plans-for-foreman-on-el7-debian-10-and-ubuntu-18-04/25008
[2] https://community.theforeman.org/t/the-el7-deprecation-checklist/28041/4

A release of this module will exist with continued EL7 support. This drop will affect the main branch of this module and the nightly Foreman ecosystem. As we remove EL7 nightly repositories this module will be broken if we do not drop the EL7 support from the module itself.

2022-06-08 08:15 UTC, alexjfisher commented
@ehelms Any chance of getting a release out that includes @jhoblitt 's https://github.com/theforeman/puppet-foreman/pull/1054 before EL7 support is removed?

2022-06-08 15:15 UTC, ehelms commented
> @ehelms Any chance of getting a release out that includes @jhoblitt 's #1054 before EL7 support is removed?

Aye, we can do that.

2022-06-22 12:56 UTC, ehelms commented
@alexjfisher @jhoblitt the requested release is available and we can cut future ones if needed https://forge.puppet.com/modules/theforeman/foreman/20.2.0

2022-06-22 16:07 UTC, ekohl requested changes
I only looked at the actual code and currently I'm not answering the "should we drop it now or keep support in the module for a while" question.

2022-06-22 16:07 UTC, ekohl commented on manifests/repos.pp
>      'RedHat', 'Linux': {
```suggestion
    'RedHat': {
```

2022-06-22 16:07 UTC, ekohl commented on manifests/repos.pp
>        }
We haven't had Fedora releases for a long time. Simplify it to `$yumcode = "el${facts['os']['release']['major']}"` perhaps? Or even inline it in the `foreman::repos::yum` declaration a few lines below.

2022-06-22 16:07 UTC, ekohl commented on spec/spec_helper_acceptance.rb
> -  # In Puppet 7 the locale ends up being C.UTF-8 if it isn't passed.
Please also drop this bit:
https://github.com/theforeman/puppet-foreman/blob/a71cb9e4b5b26549efe0f78f941ceaca00e99b20/.sync.yml#L10-L11=

2022-07-07 13:26 UTC, ehelms commented
Shall we take in this change given EL7 has been dropped from nightly and thus will be for Foreman 3.4?

2022-07-08 09:33 UTC, ekohl reviewed
If you also modify https://github.com/theforeman/puppet-foreman#foreman-version-compatibility-notes I think this can be merged.

2022-07-08 13:45 UTC, ehelms commented
Let me know thoughts on that wording.

2022-07-08 13:55 UTC, ekohl approved these changes

2022-07-08 15:06 UTC, merged