Fixes #36311 - allow configuring mod_status
theforeman/puppet-foreman pull request #1116
Opened 2023-04-18 10:52 UTC by evgeni

2023-04-18 10:59 UTC, evgeni commented on manifests/config/apache.pp
> +  }
or is that ensured (lol) by puppet cleaning modules if they are not defined?

2023-04-18 11:14 UTC, ekohl requested changes
:-1: on including this in puppet-foreman. We shouldn't configure this via Foreman because it's the wrong layer. We also have content proxies with Apache and those wouldn't be monitored then.

Users may also want to tune the IP addresses. If we want this configurable, we can simply include it in our answers file as a top level module.

2023-04-19 06:39 UTC, evgeni commented
Yeah, I can see the "but what about proxy" argument.

Wouldn't including it as a top level module in our installer expose it too much as an "API" without us being in charge of it?

2023-08-21 10:46 UTC, closed without merging

2023-08-21 10:59 UTC, evgeni commented
let's try https://github.com/theforeman/foreman-installer/pull/877 instead