Fixes #36801: Make Redis the default cache type
theforeman/puppet-foreman pull request #1134
Opened 2023-10-05 00:49 UTC by ehelms

2023-10-05 00:55 UTC, ehelms commented
Related is adding to status API but that should not block this change just enhance it -- https://github.com/theforeman/foreman/pull/9793

2023-10-16 12:30 UTC, ekohl requested changes

2023-10-16 12:30 UTC, ekohl commented on spec/classes/foreman_spec.rb
>            let(:params) { super().merge(dynflow_redis_url: 'redis://127.0.0.1:4333/') }
You're removing all assertions in this test, so it's no longer doing anything. I'd still like to test that we can still run without Redis on the same server. You can do that by specifying the Redis URL:
```suggestion
          let(:params) { super().merge(dynflow_redis_url: 'redis://127.0.0.1:4333/', rails_cache_store: {type: 'redis', 'urls': '127.0.0.1:4334}) }
```

2023-10-17 18:34 UTC, ekohl approved these changes

2023-10-17 18:34 UTC, merged