Add hammer-cli-foreman-rh-cloud package
theforeman/puppet-foreman pull request #1145
Opened 2023-11-22 10:13 UTC by ShimShtein

2023-11-22 11:02 UTC, ekohl requested changes
Please add it to https://github.com/theforeman/puppet-foreman/blob/master/spec/classes/cli_plugins_spec.rb & https://github.com/theforeman/puppet-foreman/blob/master/spec/acceptance/foreman_cli_plugins_spec.rb so it gets tested.

2023-11-22 17:02 UTC, ekohl requested changes

2023-11-22 17:02 UTC, ekohl commented on spec/acceptance/foreman_cli_plugins_spec.rb
> +        include foreman::cli::rh_cloud
This is only packaged for Red Hat, so I'd expect it to be similar to azure, kubevirt and openscap. However, it's even only packaged for Katello, whcih we don't set up. In that sense I suppose it's similar to `foreman::cli::katello` that we don't have acceptance tests for it. Just unit tests.

2023-11-23 11:05 UTC, ShimShtein commented
@ekohl Refactored the acceptance tests to incorporate the plugin the same way Katello does.
The tests are all green now!

2023-11-23 12:15 UTC, ekohl approved these changes
Thanks! https://github.com/theforeman/foreman-plugin-overview/blob/014863c694f1d1642ed8751fa193a9c3a7a1b04a/config.yaml#L394 also needs an update after this, though perhaps only after we add it to `foreman-installer`.

2023-11-23 12:15 UTC, merged